---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
card_base <- read_csv("data/CardBase.csv")
customer_base <- read_csv("data/CustomerBase.csv")
fraud_base <- read_csv("data/FraudBase.csv")
transaction_base <- read_csv("data/TransactionBase.csv")
card_base
customer_base
fraud_base
transaction_base
```

```{r}
join <- inner_join(card_base, customer_base, by = "Cust_ID")
join
```

```{r}
join1 <- left_join(fraud_base, transaction_base, by = "Transaction_ID")
join1
```

```{r}
inner_join(card_base, transaction_base, by = c("Card_Number" = "Credit_Card_ID"))
```

```{r}
hats <- read.csv("data/hat_observations.csv")
hats
```

```{r}
hat_color_type <- hats %>% 
  separate(
          col = (observation),
          into = c("hat_color", "hat_type"),
           sep = (",")
   )
hat_color_type
```

```{r}
hat_dates <- hat_color_type %>% 
  unite(date,
    c("day", "month", "year")
  )
hat_dates
```

```{r}
hat_dates %>% 
  filter(hat_type == "beret")
```

```{r}
inner_join(join, join1, by = c("Card_Number" = "Credit_Card_ID"))
```

```{r}
exams <- read_csv("data/exam_scores.csv")
exams
```

```{r}
exams %>% 
  pivot_longer(cols = starts_with("exam"),
              names_to = "exam_question", 
              values_to = "score") 
```

