---
title: "citi_bikes_report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Domain knowledge (1.1)


# Business requirements (1.2)

# Business processes and data flow (1.3)

# Data visualisation as a tool for decision-making (1.4)

# Data types (1.5)

# Data quality and data bias (1.6)

# Preparing data for visualisation (1.7)

```{r}
library(tsibbledata)
library(tsibble)
library(lubridate)
library(tidyverse)

nyc_bikes_df <- nyc_bikes
nyc_bikes_df <- as_tsibble(nyc_bikes_df)

nyc_bikes_df <- nyc_bikes_df %>% 
  mutate(year = lubridate::year(start_time),
         month = lubridate::month(start_time),
         day = lubridate::day(start_time))
```

```{r}
hire_month <- nyc_bikes_df %>% 
  index_by(month) %>% 
  summarise(hire_count = n())

hire_month
```

```{r}
hire_month %>% 
  ggplot(aes(x = month, y = hire_count)) +
  geom_line()
```


# Process and design (2.1, 2.7, 2.8, 2.9)

# Visualisations (2.2, 2.3, 2.4, 2.5, 2.6)

# Conclusions
